### ISSUE TITLE
请求增加上传自动重试功能

### ISSUE THREAD

**Issue by wegood9** [cnbeining/onedrivecmd#20]
上传一堆大文件太痛苦了，不能上传文件夹，用*.*上传又不稳定，动不动程序就退出，而且程序退出后已上传的文件~~貌似还不会保存~~是可以保存的，quota查询的已用容量不太准。
所以可否加入对每个文件的自动重试以增强多文件上传体验？

**Comment by cnbeining** [comment]
我还是想让这东西变成stateless的。

自动重试的办法不错 但是我需要想个办法知道是否上传成功。

**Comment by wegood9** [comment]
也就是说，现在没有什么好办法解决这个问题，只能自己手动重试咯。
