### ISSUE TITLE
Running onedrivecmd from another pyhton script

### ISSUE THREAD

**Issue by aurotripathy** [cnbeining/onedrivecmd#22]
Thank you for this package.
I'm a novice python user.
I've installed onedrivecmd with pip.
The following does not work.

```
import onedrivecmd
onedrivecmd.main('quota')
```

```
(py36) C:\Users\autrip\Documents\charting\one-drive>ipython
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 10:22:32) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import onedrivecmd

In [2]: onedrivecmd.main('quota')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-a8e8966c1b54> in <module>()
----> 1 onedrivecmd.main('quota')

AttributeError: module 'onedrivecmd' has no attribute 'main'

In [3]:
```

**Comment by cnbeining** [comment]
Hi,

Long story short: onedrivecmd is a **command line utility**, and is not designed to work this way.

I've noticed that you are trying to use onedrivecmd with Jupyter Notebook. Actually Jupyter has the ability to accept Shell input:

For example, for your case, in Jupyter's code block, you can type:

```
! onedrivecmd quota
```

and should expect the except output as you would have in Shell.

I would like to add a side note here: Jupyter(or any non-interactive Shell users) may have problem initializing the utility. There are 2 ways you can fix the problem:

1. Do the init on your own machine, copy the ~/.onedrive.json to the remote machine.

2. Refer to https://stackoverflow.com/a/47894579/2946714 <https://stackoverflow.com/a/47894579/2946714> :

If you are not changing the builtin client_id, go to the correct URL below before you conduct the init process:

```
Personal:
https://login.live.com/oauth20_authorize.srf?client_id=aeba6391-92fd-437d-a9d9-33a258b96c4e&response_type=code&redirect_uri=https%3A%2F%2Fod.cnbeining.com&scope=wl.signin+wl.offline_access+onedrive.readwrite <https://login.live.com/oauth20_authorize.srf?client_id=aeba6391-92fd-437d-a9d9-33a258b96c4e&response_type=code&redirect_uri=https://od.cnbeining.com&scope=wl.signin+wl.offline_access+onedrive.readwrite>

Business:
https://login.microsoftonline.com/common/oauth2/authorize?client_id=6fdb55b4-c905-4612-bd23-306c3918217c&response_type=code&redirect_uri=https%3A%2F%2Fod.cnbeining.com <https://login.microsoftonline.com/common/oauth2/authorize?client_id=6fdb55b4-c905-4612-bd23-306c3918217c&response_type=code&redirect_uri=https://od.cnbeining.com>
```
(You can edit the URL if you need to)

conduct the authorization, and copy the authorization code.

Now go to Jupyter, execute the following code line:

```
! printf 'REPLACE_ME_WITH_YOUR_CODE\n' | onedrivecmd init(_business)
```

Onedrivecmd will finish the init process with the code provided.

**Comment by aurotripathy** [comment]
Thank you.
