### ISSUE TITLE
The get command cannot write to another folder in windows 10

### ISSUE THREAD

**Issue by aurotripathy** [cnbeining/onedrivecmd#23]
In the example below the "input" folder exists and I want the downloaded file to be written into that folder.

```
(py36) C:\Users\autrip\Documents\charting\charting>onedrivecmd get "od:/Data Center Weekly Update.xlsx" input
[KDownloading |################################| 100.0% - 0s
[?25hWARNING:root:File input do not exist!
```

**Comment by cnbeining** [comment]
I would consider that as a feature request.

However I would rather keep the argument handling in this way so the utility can download multiple remote files in one command.

**Comment by aurotripathy** [comment]
ok, thanks. 
I was following the command syntax which indicates i can write to the /tmp folder

`onedrivecmd [OPTIONS] get od:/foo/file.txt /tmp/ `

**Comment by BearDic** [comment]
I've fixed this problem and a PR is coming soon.
