### ISSUE TITLE
在老毛子路由器运行出现ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by xiban148** [cnbeining/onedrivecmd#25]
![q -20180512005853](https://user-images.githubusercontent.com/21142462/39936728-068b83c6-5580-11e8-8833-1736424e7567.png)

**Comment by cnbeining** [comment]
是Python 3吗？

但是我应该保证Python2和3是兼容的。。。你试试```pip3 install onedrivecmd```？

BTW：毛子路由器我不敢保证编码问题。。。我可能没处理好Corner cases。。。

**Comment by Alog148** [comment]
有试过python3
我想发截图但是断网了。
![q -20180512010328](https://user-images.githubusercontent.com/21142462/39953709-d11525b2-55e3-11e8-9486-76d0e94c80f7.png)
这个是pip3 install onedrivecmd的错误
![q -20180512125706](https://user-images.githubusercontent.com/21142462/39953716-fc9f1c1a-55e3-11e8-920e-8e37c4f6733d.png)
运行环境是entware

**Comment by cnbeining** [comment]
```sudo pip3 install --upgrade setuptools```

试试？

**Comment by Alog148** [comment]
失败了，我放弃了。
![q -20180513165902](https://user-images.githubusercontent.com/21142462/39965609-f68304fe-56ce-11e8-90c1-954e4d68258a.png)

**Comment by Alog148** [comment]
失败了，估计不行
![q -20180513165902](https://user-images.githubusercontent.com/21142462/39965616-0e28b2d4-56cf-11e8-9de0-40d0ccc70474.png)

**Comment by cnbeining** [comment]
哦你的内存太小了。。路由器嘛

你看看是不是有交叉编译好的？

**Comment by BearDic** [comment]
no more updates
