### ISSUE TITLE
[Question]离线下载

### ISSUE THREAD

**Issue by Zxilly** [cnbeining/onedrivecmd#29]
**关于离线下载的api**
这是个人版的
https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/api/driveitem_upload_url
这是企业版的
https://docs.microsoft.com/zh-cn/connectors/onedriveforbusiness/#copyfile
用来获取下载进度的
https://docs.microsoft.com/zh-cn/onedrive/developer/rest-api/concepts/long-running-actions
那么神奇的问题来了，我在Office Flow中调用此API只能传50m以下的文件，请问您是怎么实现传大文件的？

**Comment by cnbeining** [comment]
我只是做一个API call 并没有真正测试过大文件。
