### ISSUE TITLE
教育账号返回undefined

### ISSUE THREAD

**Issue by likebeta** [cnbeining/onedrivecmd#3]
某些edu账号(比如live.shop.edu.cn)访问生成的授权链接直接返回undefined

**Comment by cnbeining** [comment]
请提供更多细节？

**Comment by yanyuechuixue** [comment]
同样发生了这个问题。输入验证授权链接在地址栏，回车以后，显示undefined

**Comment by cnbeining** [comment]
啧。

我可能得开一个这种账号试一下：已知问题是某些账号是不能连第三方app的，需要管理员手工批准。所以这个项目的readme这么长。

有这种渠道请邮件我一下怎么注册，我跑一下看看是为什么。也许这个bug修不了，做好心理准备吧。

**Comment by poboc** [comment]
国内的edu账号好像不行，企业账号可以

**Comment by dzhuangvanhawks** [comment]
有可能是这里：

https://github.com/cnbeining/onedrivecmd/wiki/How-to-create-your-own-application-to-use-with-onedrivecmd

不是管理员有可能没法生成key。我生成的key不可用，有可能是

- 我的号整个翻车了
- key只能在自己的域里用 不能跨域使用。

后者无解 我觉得就是这种情况。

**Comment by cnbeining** [comment]
上了个别的edu车 可以。

这个问题肯定是因为管理员的权限设置。

**Comment by cnbeining** [comment]
有点明白为什么了：

某些edu账号有可能没有管理员。

没有管理员的edu域拿不到验证码。

偷个图：

![image](https://user-images.githubusercontent.com/1560962/29204511-75d98902-7e45-11e7-87f6-c51cfd5103ab.png)

不是一个软件 但是问题一样。
