### ISSUE TITLE
可否增加上传“文件夹”的功能？

### ISSUE THREAD

**Issue by ttestdock** [cnbeining/onedrivecmd#5]

**Comment by cnbeining** [comment]
我记得有可能写过这个功能 但是不稳定来着。。。

2017年3月21日 上午10:17，"ttestdock" <notifications@github.com>写道：

**Comment by BearDic** [comment]
功能已添加, 谢谢. 

In #24:
> 谢谢, 功能已添加, 使用 dfs 实现. 实践表明并不需要提前 `mkdir`, 上传的时候会自动创建.
> 
> 参见: #41
