### ISSUE TITLE
可以下载文件但是不能下载整个目录

### ISSUE THREAD

**Issue by FFFcat** [cnbeining/onedrivecmd#51]
onedrivecmd get od:/math.sc/ 提示WARNING:root:File od:/math.sc/ do not exist!

**Comment by cnbeining** [comment]
貌似目前还没这个feature.... 欢迎大佬们PR。

**Comment by BearDic** [comment]
应该是可以的啊……我在根目录创建了一个 `math.sc` 文件夹, 然后在里面随便放点东西, 可以下载, 如图: 

![QQ截图20190612091337](https://user-images.githubusercontent.com/41772157/59316720-6ff7dd00-8cf2-11e9-9632-21a4fb64d014.png)

检查一下是否有升级到最新版本?

**Comment by BearDic** [comment]
这是在 #49 加入的新功能, 版本号是 0.1.8

**Comment by FFFcat** [comment]
> 这是在 #49 加入的新功能, 版本号是 0.1.8

Ok，谢了…原来是termux的Python拉的版本太低了。。
