### ISSUE TITLE
上传错误KeyError: 'uploadUrl'

### ISSUE THREAD

**Issue by godzlalala** [cnbeining/onedrivecmd#6]
root@ns3032500:~/onedrivecmd#  python onedrivecmd.py put ./README.md od:/mp4/
Traceback (most recent call last):
  File "onedrivecmd.py", line 79, in <module>
    main()
  File "onedrivecmd.py", line 61, in main
    do_put(client, args)
  File "/root/onedrivecmd/utils/actions.py", line 300, in do_put
    chunksize = int(args.chunk))
  File "/root/onedrivecmd/utils/uploader.py", line 67, in upload_self
    uploadUrl = req.json()['uploadUrl'].encode('utf-8')
KeyError: 'uploadUrl'

**Comment by cnbeining** [comment]
有点尴尬 因为我没Onedrive号了（全翻车啦） 所以debug有点困难。。。

![yn 7xm cz2 d s hi z5](https://cloud.githubusercontent.com/assets/1560962/25095898/9edb8e02-236b-11e7-8865-09ca6346b6a5.jpg)


我会尝试复现的。

**Comment by godzlalala** [comment]
需要onedrive帐号嘛，我可以提供

**Comment by shouko** [comment]
遇到同樣的問題 我是 Business 版的

**Comment by cnbeining** [comment]
能偶尔复现但不知道原因。

已知在上传频率较快时容易出现。

怀疑是微软的小霸王服务器受不了压力。

**Comment by BearDic** [comment]
看了当年的代码……正好就是这之后的下一个 commit 中在 uploader.py 加入了对 requests 状态码的检查

```
    if req.status_code > 201:
        print(req.json()['error']['message'])
        return False
```

所以我猜大概就是 #41 的问题吧, 也过去这么久了……
