### ISSUE TITLE
onedrivecmd is disabled

### ISSUE THREAD

**Issue by cklatsky** [cnbeining/onedrivecmd#79]
Hi,

After running `onedrivecmd init_business` and then copying & pasting the URL into the browser, the following error is returned in the browser and not returning an auth token.  Is there any way around this issue?

Request Id: 21283e49-1648-4ed2-b53f-52508d7b3e00
Correlation Id: f35a1170-a3b1-4487-ba69-d107058db006
Timestamp: 2021-02-12T15:53:39Z
Message: AADSTS7000112: Application '6fdb55b4-c905-4612-bd23-306c3918217c'(onedrivecmd) is disabled.

**Comment by cnbeining** [comment]
You will need to bring your own AAD application: Azure does not allow
other’s applications running in your AD without permission from global
admin.
